version: '3'

networks:
  suomec-ovalidator-network:
    driver: bridge

services:
  suomec-ovalidator-php81:
    container_name: suomec-ovalidator-php81
    build:
      context: ./var/docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
      - ./var/docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - suomec-ovalidator-network
